### ISSUE TITLE
Advanced Demo link is broken

### ISSUE THREAD

**Issue by elgs** [flatlogic/widgster#3]
Thanks for the nice lib. It's incredibly useful, but the advanced demo link seems to be broken.

**Comment by okendoken** [comment]
Hi @elgs 
here is the updated link http://demo.flatlogic.com/sing-wrapbootstrap-2/ajax/grid.html
We'll update the readme too.

Thanks for pointing this out

**Comment by elgs** [comment]
Thank you so much.
