### ISSUE TITLE
TypeError: Cannot read property 'Constructor' of undefined

### ISSUE THREAD

**Issue by vredchenko** [flatlogic/widgster#4]
Hi, I'm using widgster in a project with a port of Sing template, am getting the following error:

`TypeError: Cannot read property 'Constructor' of undefined`
from:
`jQuery.fn.widgster.Constructor.DEFAULTS.bodySelector = '.widget-body';`

Have I missed an initialisation step?

The directive I use is ripped from Sing Demo (AngularJS regular):

```
/* ========================================================================
 * Widgster Wrapper. Triggered for all .widget's
 * ========================================================================
 */
function widget($document){
  /**
   * Setting Widgster's body selector to theme specific
   * @type {string}
   */
  jQuery.fn.widgster.Constructor.DEFAULTS.bodySelector = '.widget-body';

  /*
   When widget is closed remove its parent if it is .col-*
   */
  jQuery($document).on('close.widgster', function(e){
    var $colWrap = jQuery(e.target).closest('.content > .row > [class*="col-"]:not(.widget-container)');

    // remove colWrap only if there are no more widgets inside
    if (!$colWrap.find('.widget').not(e.target).length){
      $colWrap.remove();
    }
  });
  return {
    restrict: 'CEA',
    link: function(scope, $el, attrs){
      if (attrs.postProcessing === 'true') return;
      $el.widgster();
    }
  }
}

widget.$inject = ['$document'];

module.exports = widget;
```

**Comment by jboothe** [comment]
Same issue here with Angular 2 version. 

```
import {Directive, ElementRef, OnInit} from '@angular/core';
declare var jQuery: any;

@Directive ({
  selector: '[widget]'
})
export class Widget implements OnInit {
  $el: any;
  constructor(el: ElementRef) {
    this.$el = jQuery(el.nativeElement);
    jQuery.fn.widgster.Constructor.DEFAULTS.bodySelector = '.widget-body';

    jQuery(document).on('close.widgster', (e) => {
      let $colWrap = jQuery(e.target)
        .closest('.content > .row > [class*="col-"]:not(.widget-container)');

      // remove colWrap only if there are no more widgets inside
      if (!$colWrap.find('.widget').not(e.target).length) {
        $colWrap.remove();
      }
    });
  }

  ngOnInit(): void {
    this.$el.widgster();
  }
}
```

**Comment by rohitBaravkar** [comment]
hi @vredchenko  I have same issue with Sing Template have you resolve it?

Thanks,

**Comment by vredchenko** [comment]
hi @rohitBaravkar, I honestly don't remember how it was solved (or if it was) and I no longer work on the project nor have access to the codebase. Perhaps one thing you could try is to update dependencies.. Sorry I could not be of more help

**Comment by rohitBaravkar** [comment]
NP @vredchenko I will  try by updating dependencies

**Comment by yamrita** [comment]
Is there any update on this? Having the same issue with Angular 2.

**Comment by joerg-bergner** [comment]
Hi!
My solution was to put following line
`"../node_modules/widgster/widgster.js",`
into scripts section in angular-cli.json

**Comment by chami85** [comment]
Hello,
Had the same issue on an Angular 2+ project (Jhipster) using webpack
My solution was to edit the widgster.js itself by adding :

`import $ from 'jquery';
global.$ = global.jQuery = $;`

Hope it helps.

**Comment by WhoSV** [comment]
Hye
same issue after updating to Webpack 4..

Thanks

**Comment by thecodemonk** [comment]
Depending on your webpack config, you may have to put 
import 'widgster';
into your directive to get webpack to load the widgster script for you. I had this same problem after upgrading to angular 6 and webpack 4, where it was working previously just find in angular 5/webpack 3.
